services:
  - type: web
    name: dreamz-expo-server
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: EXPO_TUNNEL
        value: 'true'
    autoDeploy: true
    healthCheckPath: /
